### ISSUE TITLE
Changing FreeRTOS Tick rate

### ISSUE THREAD

**Issue by ankitbhatia** [tsandmann/freertos-teensy#4]
I wanted to run the freeRTOS port with a tick rate of 10kHZ. Do I need to change anything else except the 

`#define configTICK_RATE_HZ ( (TickType_t) 10000 )`

in FreeRTOSConfig.h?

**Comment by tsandmann** [comment]
Unfortunately yes, because all the Arduino timing functions rely on one tick every millisecond.

You could try to change `void vApplicationTickHook()` as the following:
- for teensy 4.x in port/teensy_4.cpp
  ```c++
  void vApplicationTickHook() {
      static uint32_t n {};
      if (++n == configTICK_RATE_HZ / 1'000UL) {
          systick_cycle_count = ARM_DWT_CYCCNT;
          systick_millis_count = systick_millis_count + 1;
          n = 0;
      }
  }
  ```
 - for teensy 3.x in port/teensy_3.cpp
    ```c++
    void vApplicationTickHook() {
        static uint32_t n {};
        if (++n == configTICK_RATE_HZ / 1'000UL) {
            systick_millis_count = systick_millis_count + 1;
            n = 0;
        }
    }
    ```

But I haven't tested that yet. I'll try to include a solution for different  tick rates in the next release (or at least a warning for unsupported tick rates).
